### ISSUE TITLE
'Breaks are Good' achievement inconsistencies

### ISSUE THREAD

**Issue by tobbez** [immortalityidle/immortalityidle.github.io#102]
- Description claims the achievement requires 2 hours' worth of offline ticks
- Hint claims it's "a day"
- Comment on hint's line claims it's 20h (close enough to the hint's day)
- The condition seems to intend for 2h
- The actual required time is 20h, because the condition fails to account for `MainLoopService.offlineDivider`

For reference:

https://github.com/immortalityidle/immortalityidle.github.io/blob/a69779dc967b7431605917f5deccae658fca0827/src/app/game-state/achievement.service.ts#L698-L703

https://github.com/immortalityidle/immortalityidle.github.io/blob/a69779dc967b7431605917f5deccae658fca0827/src/app/game-state/main-loop.service.ts#L107-L109

https://github.com/immortalityidle/immortalityidle.github.io/blob/a69779dc967b7431605917f5deccae658fca0827/src/app/game-state/main-loop.service.ts#L45

**Comment by 1234abcdcba4321** [comment]
I created this achievement intending for 20h. The description could probably be changed; I wrote 2 there as you do collect 2 hours of banked ticks, but the 10x inefficiency makes getting those 2 hours take 20 hours to collect.

**Comment by tobbez** [comment]
Sounds like the description could use and update then, yes.

The problem with the current wording is that it can easily be interpreted as "the number of offline ticks received from 2 hours of offline time" when it actually means "the number of ticks that results in 2 hours when converted back into time at the standard tick rate".

(I agree the hints don't need to be perfectly accurate, which is why the initial post stated it was 'close enough'.)
