### ISSUE TITLE
Lifespan from stats

### ISSUE THREAD

**Issue by ChucklesTheBeard** [immortalityidle/immortalityidle.github.io#153]
Is this intended to be practically nothing for several days, despite showing up in the first minutes of gameplay? I recently noticed it went up to a whopping 1 year, after about 5 million days lived.

![image](https://user-images.githubusercontent.com/12536545/183762613-6293a5fe-2e90-423b-93d1-b8c07d1e997c.png)

**Comment by kagejohn** [comment]
Life span from basic attributes is your total aptitudes put through the same function that gives multipliers for attributes divided by 5 and the output of that is divided by 10.
That number is in days so until you get to bloodline rank 5 it isn't a very large amount, at bloodline rank 5 the last divisor is removed.
Any counter for life span shows up when it is above 0 days

**Comment by immortalityidle** [comment]
Working as intended, thanks for checking though.
