### ISSUE TITLE
v1.0.55 popups sticking

### ISSUE THREAD

**Issue by ChucklesTheBeard** [immortalityidle/immortalityidle.github.io#157]
Sometimes, popups aren't going away until I refresh the page. I can't reliably reproduce the issue every time, but during normal play it happens fairly frequently in Firefox 103.0.2. I couldn't get it to happen in Chrome.

![image](https://user-images.githubusercontent.com/12536545/184155142-8c037b8a-7342-4896-94ea-4335ef5de3aa.png)

Pictured: two popup descriptions stuck; one inventory item and one "dismiss follower"; the mouse is hovering over an action button showing a third popup to demonstrate that it wasn't moved very recently.

This is new in 1.0.55, I never saw it happen in 1.0.54.

**Comment by immortalityidle** [comment]
We were planning to change the tooltips anyway for better accessibility. I'll push that ahead in the schedule. Probably won't be for another week or two though.

**Comment by immortalityidle** [comment]
This should be fixed on the experimental build now. @ChucklesTheBeard can you check and confirm?
