### ISSUE TITLE
Negative damage to late-game boss

### ISSUE THREAD

**Issue by ResidualToast** [immortalityidle/immortalityidle.github.io#161]
I am dealing negative damage to Death despite seeming to have much higher stats (496T attack/244T def, 5-10T attribute stats, mana strike and shield on).
[Immortality_Idle_v1.0.55_2022-08-15T18 58 23.769Z.txt](https://github.com/immortalityidle/immortalityidle.github.io/files/9339286/Immortality_Idle_v1.0.55_2022-08-15T18.58.23.769Z.txt)

**Comment by kagejohn** [comment]
That seems to be a bug related to the coming feature where you can damage multiple enemies at the same time.
Your damage isn't actually negative, what it is showing in error is your damage minus the enemies health.
