### ISSUE TITLE
I dont know what exactly is wrong.....

### ISSUE THREAD

**Issue by YiZhuYe** [immortalityidle/immortalityidle.github.io#170]
[Immortality_Idle_v1.0.58_2022-08-23T05 01 37.839Z.txt](https://github.com/immortalityidle/immortalityidle.github.io/files/9399510/Immortality_Idle_v1.0.58_2022-08-23T05.01.37.839Z.txt)

Here is my save file. 

Most menus tend to free the game and make the screen non-interactable. The buttons all seem to have their "code" text as well as the intended display text. 

The enemies are being generated with weird negative health.

The game pauses every 1 second. 

My nutrition is stuck at 0 and my health is stuck at 504.

**Comment by immortalityidle** [comment]
Looks like you somehow got an undefined item in your inventory, which caused an infinite error spiral. Not sure how that happened, but the attached file should be your game with that fixed
[Immortality_Idle_v1.0.58_2022-08-23T05_43_43.894Z.txt](https://github.com/immortalityidle/immortalityidle.github.io/files/9399680/Immortality_Idle_v1.0.58_2022-08-23T05_43_43.894Z.txt)
.

**Comment by YiZhuYe** [comment]
Thank you very much for the fix!
