### ISSUE TITLE
Game crashes on Chrome browser after some time.

### ISSUE THREAD

**Issue by Enover** [immortalityidle/immortalityidle.github.io#173]
This is the save
[Immortality idle.txt](https://github.com/immortalityidle/immortalityidle.github.io/files/9440103/Immortality.idle.txt)

**Comment by A-Strange-Ball1234** [comment]
I'll check it in an incognito window.

**Comment by Enover** [comment]
[Immortality idle test 2.txt](https://github.com/immortalityidle/immortalityidle.github.io/files/9440116/Immortality.idle.test.2.txt)

**Comment by kagejohn** [comment]
How long is "some time"?
Looking at Chrome's task manager, nothing odd is happening, it slowly grows and then it falls down again.

**Comment by Enover** [comment]
From what I remember it did not take more then 10 min
let me time it this time

**Comment by Enover** [comment]
Ok from what I see about 9 min it takes for my game to crash while running it on chrome. Error code out of memeory it says

**Comment by kagejohn** [comment]
Odd, are you doing anything special beside just letting it run? as nothing has happened on my end.
Another thing that could be the issue, how much RAM does your system have?

**Comment by Enover** [comment]
16 gigs on my system

**Comment by Enover** [comment]
I checked my broswer Cache and it was at 300gigs but that was cleared so it cant be that

**Comment by kagejohn** [comment]
Hmm, then memory shouldn't be an issue.
Can you check Chrome's task manager to see if "Memory footprint" for the tab goes up by a lot?
For me it goes to around ~230 MB and then falls to ~130 MB.

**Comment by Enover** [comment]
my google grom task manager is getting around 1,400.000K and its slowly rising

**Comment by Enover** [comment]
Ok so it seems to cap off around 2,118,000K or so before droping to 1,780,000K and just hovers around that area

**Comment by kagejohn** [comment]
I am not seeing the same so it is difficult for me to say what is wrong: 
![image](https://user-images.githubusercontent.com/9349493/187088974-3bf7ea5e-c886-447c-9b8f-e3bfa807a4ec.png)

**Comment by Enover** [comment]
I will just play it though my other browser cause its not crashed once. looks like Opera GX is going to be my idle browser from now on.

**Comment by Enover** [comment]
![image](https://user-images.githubusercontent.com/45541812/187089261-496641e0-2319-4a39-b14d-ec4870263a18.png)

**Comment by Enover** [comment]
it hits 2.5mill K then crashes. it just keeps it up till it cant handle it no more.

**Comment by Enover** [comment]
and this time it only took 6 or so minutes

**Comment by immortalityidle** [comment]
Turns out it was an adblocker extension. Closing it out.
