### ISSUE TITLE
"Pause on Death" doesn't immediately stop.

### ISSUE THREAD

**Issue by OneOfMany07** [immortalityidle/immortalityidle.github.io#23]
As the title says, when using one of the higher speeds the pause on death feature doesn't trigger until after some work was done.

I've seen this a number of times using the highest speed I've unlocked (3rd box after pause... play with line on right).  On the next life I've had one turn happen.  I swear I even saw this but no days (today I was at 18 yrs 1 day when it paused).  I've seen it lock away other apprentice choices.  This time I had a Gathering Herbs trigger (2 rotten patchouli in inventory with the other after reincarnation items I expect).

Happens both on Chrome and Firefox.  v1.0.36 game version displayed

**Comment by immortalityidle** [comment]
Should be fixed in the latest build.
