### ISSUE TITLE
Miscalculation when log records repeated events and "Show" checkboxes are toggled

### ISSUE THREAD

**Issue by WilliamRoyNelson** [immortalityidle/immortalityidle.github.io#26]
Toggling the "Show" checkboxes for log messages cause repeated events (e.g., You made scaffolding (2)) to display inaccurate values.

Original state
![image](https://user-images.githubusercontent.com/7910938/179335910-764c3434-7cd0-44be-b6f2-f3791fbf97b3.png)
Deselect "Show Event Messages"
![image](https://user-images.githubusercontent.com/7910938/179336003-cf3e36bb-e70b-4682-ba3d-2acb778fe3d4.png)
Re-select "Show Event Messages"
![image](https://user-images.githubusercontent.com/7910938/179336079-59524e96-ca92-429a-bada-725dd452f429.png)

**Comment by WilliamRoyNelson** [comment]
I'm not very good at Typescript, but I _think_ it's something going on with this function:
https://github.com/immortalityidle/immortalityidle.github.io/blob/dda0c70f038a0efe06ebcbcb9080354893dd078d/src/app/game-state/log.service.ts#L116-L128

Or maybe here? I think it's trying to increment the values at times that it's not correct.

https://github.com/immortalityidle/immortalityidle.github.io/blob/dda0c70f038a0efe06ebcbcb9080354893dd078d/src/app/game-state/log.service.ts#L78-L101

It also affects messages further down in the logs  (Toggling Show Event Messages on, then back off)
![image](https://user-images.githubusercontent.com/7910938/179336449-77c92aa9-d4ec-4cfc-8d3f-e46b205ec04f.png)
![image](https://user-images.githubusercontent.com/7910938/179336457-748a4ea6-0482-4f53-948d-ada7bcfc3956.png)
![image](https://user-images.githubusercontent.com/7910938/179336463-58baa3de-b321-4a57-ac5a-67aa6f943374.png)

**Comment by ChandlerFerry** [comment]
Taking a look.

**Comment by ChandlerFerry** [comment]
For transparency, I've found the problem but removing it causes a significant tick efficiency loss in the current model.

As such, I am investigating a better solution for managing logging.
