### ISSUE TITLE
Inventory tiles and actions jump around based on item names.

### ISSUE THREAD

**Issue by threehams** [immortalityidle/immortalityidle.github.io#29]
The tiles in the inventory panel jump around based on the names of the items in them. This can make it difficult to merge gems manually, among other things.
![Screenshot - 7_16_2022 , 1_07_21 PM](https://user-images.githubusercontent.com/1399894/179370665-d14ce7b6-76a1-40a7-8925-2bbabf750efc.png)
 
It's not clear what the ideal solution is here, though:
- Change to 4 tiles wide?
- Shorten some modifiers to better fit?
- Truncate very long text (CSS can do this now)?
- Switch to colored icons for weapons, and show name only on hover?

**Comment by immortalityidle** [comment]
Ideally I'd like to iconize everything and color-code based on quality, but that's a pretty big task and would require decent icons for everything. Maybe we'll truncate in the short term.

**Comment by immortalityidle** [comment]
Fixed! Thanks @Ch1pless
