### ISSUE TITLE
Shift + click not working on Firefox?

### ISSUE THREAD

**Issue by OneOfMany07** [immortalityidle/immortalityidle.github.io#3]
Not sure if you use a certain browser to develop and test with, but in Firefox (Windows 10 x64, latest stable version I'm pretty sure) shift + right click isn't selling all of an item (rice).  Instead I get the usual right click context menu (icon row at top to go forward or back, save page as..., etc).

And shift clicking the stack eat button at the bottom isn't filling me up, though I think it might have worked once.  Also when I fill my nutrition bar it immediately loses one notch (might be expected, but felt odd to see it over and over).

Thanks for sharing your game, and making it open source!  Could be nice to have a link in game to here, in case someone doesn't know how to find it.

**Comment by OneOfMany07** [comment]
Oh the inventory area gets a scroll bar too.  With all the boxes REALLY far apart vertically.  Like 3 active rows max (with shanty or shack or whatever).

**Comment by immortalityidle** [comment]
Firefox support is on my list of things to do for the game, but it's pretty low on the list. Firefox has special handling for shift+right click that I don't think I can override https://bugzilla.mozilla.org/show_bug.cgi?id=897379 so I'm not sure I'll ever be able to do anything about that one.

**Comment by immortalityidle** [comment]
Alt-click now does everything shift-click would.
