### ISSUE TITLE
Inventory Scrollbar moves down automatically

### ISSUE THREAD

**Issue by Ch1pless** [immortalityidle/immortalityidle.github.io#57]
The inventory scrollbar moves a step down when the leftmost slot of any row occluded above by the inventory header is updated.

**Comment by kagejohn** [comment]
I found a solution to this problem: https://stackoverflow.com/questions/48585358/how-do-i-prevent-chrome-from-scrolling-when-angular-5-rerenders-a-large-list

**Comment by BeagleGaming1** [comment]
![image](https://user-images.githubusercontent.com/56142455/180668362-cef3781a-d06e-47b0-a087-a1e3432ced9b.png)
https://css-tricks.com/almanac/properties/o/overflow-anchor/

**Comment by immortalityidle** [comment]
Fixed in 1.0.50.
