### ISSUE TITLE
Potential getAttributeStartingValue bug

### ISSUE THREAD

**Issue by Dankaati** [immortalityidle/immortalityidle.github.io#6]
https://github.com/immortalityidle/immortalityidle.github.io/blob/41b61dc5b6fc0521ff3c20cdf4441281d85d2399/src/app/game-state/character.ts#L366

(this.attributeScalingLimit * (this.attributeSoftCap - 100) / 100) should maybe be ((this.attributeScalingLimit - (this.attributeScalingLimit * 100)) / 100)

Note that currently there is a big jump from attributeSoftCap-1 to attributeSoftCap (about 1.1k -> 10k). Also note that this is a huge balance change moving multi at softcap from 10k to about 1.1k, so if the old balance was preferred maybe softcap should be raised in turn.

**Comment by Dankaati** [comment]
Also note that since spirituality based lifespan uses this function, it would be currently impossible to reach grade 16 moster core without this bug.

**Comment by Dankaati** [comment]
Third note: This made the multiplier at softcap scale pretty well with meridans. This is not really true anymore if only this change is made, it might be reasonable to make meridans also double softcap. Even with all this, this would amount to a nerf compared to current state.

**Comment by immortalityidle** [comment]
I don't want to introduce a nerf, so let's just call it good as-is.
