### ISSUE TITLE
All functionality has stopped / visual errors

### ISSUE THREAD

**Issue by SirBriguy** [immortalityidle/immortalityidle.github.io#67]
At some point after todays update (adjusted followers control) when I clicked on the followers gear icon, my game got borked. Now none of the activities are showing and no buttons work. The text in all the window panes are overlapping etc.
If I click on the top menu buttons, they bring up a dialog box, but then I can't dismiss it or anything.
I tried importing my save to a different browser and the same thing happened.
System Specs
Windows 10, Chrome (also tried FireFox)

For reference, I just loaded it up in Chrome again to get the save data and it seems to have fixed itself. But when I loaded it in Firefox, it was still borked. Here is the save from Firefox
[immortalityIdle.txt](https://github.com/immortalityidle/immortalityidle.github.io/files/9160866/immortalityIdle.txt)
.

**Comment by immortalityidle** [comment]
Looks like something funny happened that got you saved with an impossible task in your schedule but no impossible task running. I'll look into making sure
 that it doesn't happen in future builds. In the meantime, I think the attached save should get you back to where you were.
[immortalityIdle_fixed.txt](https://github.com/immortalityidle/immortalityidle.github.io/files/9162727/immortalityIdle_fixed.txt)
