### ISSUE TITLE
Random things

### ISSUE THREAD

**Issue by pacak** [immortalityidle/immortalityidle.github.io#7]
1. When going full speed weapon and armor merging can't keep up with crafting, it would be great if merger run right after item creation, or even better - just updated the corresponding item in the inventory.
2. When going full speed "Pause on Death" skips death moment and runs a few actions in the next life. It would be great to stop right when the new life starts, or even better - a few days before it starts so you can deal with merging final bits of equipment, currently you have to closely monitor the game if you want to do that - not in a fun way.
3. ~~Mass "monster core" upgrades. Ctrl-click. I have autoclicker but it's not fun.~~
4. Furniture shop QOL: currently shop tries to buy the same items as in the previous life, it would be great if it went with buying earlier versions as well. It might not be able to afford the fanciest bed at once but 10 coins for a blanket is affordable and works.
5. ~~Alchemy spams game log with created items. Can probably be summarized more briefly or filtered separately.~~
6. No numbers on stamina like bars in Firefox

**Comment by Jiur13** [comment]
I'd like to add to this too.

regarding number 4 - Better options for furniture would be great, maybe a little UI menu that you can tell the game that you want to buy furniture in order up to a final point of your choosing

7. The game doesn't remember when you unlock new actions so you constantly have to keep adding them back to the queue, so the "Manual of Remembered Plans" is basically useless and it makes the game EXTREMELY active heavy, you can't call it an idle game where you have to constantly micromanage every little thing. All tasks should be remembered from the past life and added to the queue when they unlock.

8. Autobuy capping out at 90% of your income so you don't get mauled to death by debt collectors randomly.

9. I know you were trying to go for "balance" when designing mana, but for an actual player it's a horrible, miserable experience. The meta is alchemy which pushes your water lore WAY higher than the others and trying to balance them all is absolutely grim, if not impossible. I propose that anything mana related just be tied to levels only, completely ignoring the "within 10% range" or whatever it currently is.

**Comment by Jiur13** [comment]
> 

i thought you had to get all 4 "elemental" lores to the same level with no less than 10% deviation? sorry that's what i read somewhere i didn't know it was tied to those 2 cultivations instead

**Comment by Kleptichron** [comment]
@Jiur13 That's what you do for unlocking mana the first time. It's not required after that.

**Comment by Jiur13** [comment]
> @Jiur13 That's what you do for unlocking mana the first time. It's not required after that.

i'm still not exactly sure what the strat for doing this is because you need alchemy to live longer and it explosively inflates your water lore, i've had runs where it gets to like 10 million where stuff like metal and fire is still in the thousands

i think it would be better if the minimum amount needed was increased, but the deviation requirement was removed
